export const addElementProps = (element, props) => ({ ...element, ...props });

export const createTemplateElement = ({ id, path }) => ({
  section: {
    id,
    path,
    target: 'section',
    spacing: 8,
    justify: 'center',
    alignContent: 'center',
    alignItems: 'center',
    style: { marginTop: '10%' },
    sizes: { xs: 10, sm: 10, md: 10, lg: 10 },
    components: {
      [`${id}-block`]: {
        id: `${id}-block`,
        path: `${path}/${id}-block`,
        target: 'block',
        sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
        components: {
          [`${id}-title`]: {
            id: `${id}-title`,
            path: `${path}/${id}-block/${id}-title`,
            target: 'title',
            gutterBottom: true,
            color: 'primary',
            align: 'right',
            sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
            components: 'Lorem Ipsum',
          },
          [`${id}-text1`]: {
            id: `${id}-text1`,
            path: `${path}/${id}-block/${id}-text-1`,
            target: 'text',
            align: 'justify',
            sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
            components: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
              sed do eiusmod tempor incididunt ut labore etdolore magna aliqua.
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
              aliquipea commodo consequat.`,
          },
          [`${id}-text2`]: {
            id: `${id}-text-2`,
            path: `${path}/${id}-block/${id}-text-2`,
            target: 'text',
            align: 'justify',
            sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
            components: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
              sed do eiusmod tempor incididunt ut labore etdolore magna aliqua.
              Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut
              aliquipea commodo consequat.`,
          },
        },
      },
    },
  },
  article: {
    id,
    path,
    target: 'article',
    justify: 'center',
    alignContent: 'center',
    alignItems: 'stretch',
    container: true,
    spacing: 16,
    sizes: { xs: 12, sm: 12, md: 10, lg: 10 },
    components: {
      [`${id}-section`]: {
        id: `${id}-section`,
        path: `${path}/${id}-section`,
        target: 'section',
        justify: 'center',
        spacing: 2,
        sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
        components: {
          [`${id}-imageTile`]: {
            id: `${id}-imageTile`,
            path: `${path}/${id}-section/${id}-imageTile`,
            actionProps: { target: 'div' },
            alt: 'halte la',
            height: '100%',
            width: '100%',
            sizes: { xs: 4, sm: 4, md: 4, lg: 4 },
            target: 'imageTile',
            data: 'https://placekitten.com/300/300',
          },
          [`${id}-block`]: {
            id: `${id}-block`,
            path: `${path}/${id}-section/${id}-block`,
            target: 'block',
            sizes: { xs: 7, sm: 7, md: 7, lg: 7 },
            components: {
              [`${id}-title`]: {
                id: `${id}-title`,
                path: `${path}/${id}-section/${id}-block/${id}-title`,
                target: 'title',
                gutterBottom: true,
                color: 'primary',
                align: 'right',
                sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
                components: 'Lorem Ipsum',
              },
              [`${id}-text`]: {
                id: `${id}-text`,
                path: `${path}/${id}-section/${id}-block/${id}-text`,
                target: 'text',
                align: 'justify',
                sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
                components: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
                      sed do eiusmod tempor incididunt ut labore etdolore magna aliqua.
                      `,
              },
            },
          },
          [`${id}-button`]: {
            id: `${id}-button`,
            path: `${path}/${id}-section/${id}-button`,
            target: 'button',
            variant: 'outlined',
            color: 'primary',
            sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
            components: 'Lorem',
          },
        },
      },
    },
  },
  block: {
    id,
    path,
    target: 'block',
    sizes: { xs: 12, sm: 12, md: 7, lg: 8 },
    components: [],
  },
  title: {
    id,
    path,
    target: 'title',
    gutterBottom: true,
    color: 'primary',
    align: 'right',
    sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
    components: 'Lorem Ipsum',
  },
  imageTile: {
    id,
    path,
    actionProps: { target: 'div' },
    alt: 'halte la',
    height: '100%',
    width: '100%',
    sizes: { xs: 12, sm: 12, md: 4, lg: 4 },
    target: 'imageTile',
    components: 'https://placekitten.com/300/300',
  },
  text: {
    id,
    path,
    target: 'text',
    align: 'justify',
    sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
    components: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,.`,
  },
  divider: {
    id,
    path,
    target: 'divider',
    sizes: { xs: 12, sm: 12, md: 12, lg: 12 },
    margin: '25px',
  },
});
